workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: adbserver.com.cafmjazan

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Flutter build iOS
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        submit_to_app_store: false